// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNFgPjqJE7VlP2beiL3AA7KZ66Eg2xXnM',
    appId: '1:876322683229:web:b2c1148e875e5cc49750b4',
    messagingSenderId: '876322683229',
    projectId: 'spotify-app-chukwunonso',
    authDomain: 'spotify-app-chukwunonso.firebaseapp.com',
    storageBucket: 'spotify-app-chukwunonso.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdIwwHsroBxUhTPVmdG_mKG1tQj5ffg9g',
    appId: '1:876322683229:android:849b5bc3e98dfbeb9750b4',
    messagingSenderId: '876322683229',
    projectId: 'spotify-app-chukwunonso',
    storageBucket: 'spotify-app-chukwunonso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19NpjI1PpbBASC5Zx9LNGnhzXdCK4O0k',
    appId: '1:876322683229:ios:429bdfd59e7f28c79750b4',
    messagingSenderId: '876322683229',
    projectId: 'spotify-app-chukwunonso',
    storageBucket: 'spotify-app-chukwunonso.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19NpjI1PpbBASC5Zx9LNGnhzXdCK4O0k',
    appId: '1:876322683229:ios:429bdfd59e7f28c79750b4',
    messagingSenderId: '876322683229',
    projectId: 'spotify-app-chukwunonso',
    storageBucket: 'spotify-app-chukwunonso.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNFgPjqJE7VlP2beiL3AA7KZ66Eg2xXnM',
    appId: '1:876322683229:web:1f7c8ad14aed0ce79750b4',
    messagingSenderId: '876322683229',
    projectId: 'spotify-app-chukwunonso',
    authDomain: 'spotify-app-chukwunonso.firebaseapp.com',
    storageBucket: 'spotify-app-chukwunonso.firebasestorage.app',
  );

}